/* Crear tablespace para el proyecto */
CREATE TABLESPACE TBSEXAMPLE
DATAFILE 'tbsexample.dbf'
SIZE 300M;

/* PERMITE EJECUCION DE SCRIPTS DENTRO DEL TABLESPACE CREADO */
ALTER SESSION SET "_ORACLE_SCRIPT"=TRUE;

/* Crear usuario */
CREATE USER user_admin03 IDENTIFIED BY mauricio
DEFAULT TABLESPACE USERS
TEMPORARY TABLESPACE TEMP
QUOTA UNLIMITED ON USERS;
/* Asignar los permisos al usuario */
GRANT CREATE SESSION TO user_admin03;
GRANT CREATE TABLE TO user_admin03;
GRANT CREATE VIEW TO user_admin03;
GRANT CREATE PROCEDURE TO user_admin03;
GRANT CREATE TRIGGER TO user_admin03;
GRANT CREATE SEQUENCE TO user_admin03;
GRANT CREATE JOB TO user_admin03;